# Generated by Django 2.2 on 2020-10-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20201026_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='Верный ли ответ?'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='lms.Course', verbose_name='Курс'),
        ),
    ]
