# Generated by Django 2.2 on 2020-11-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20201028_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название главы'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название подглавы'),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Номер подглавы'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('number', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subchapter',
            unique_together={('number', 'name')},
        ),
    ]
