# Generated by Django 2.2 on 2020-11-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20201103_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('number', 'name'), 'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
    ]
